// src/components/UserAvatar.vue
<template>
  <div
    class="user-avatar"
    :style="{
      backgroundColor: color,
      width: size + 'px',
      height: size + 'px',
      fontSize: Math.round(size * 0.42) + 'px'
    }"
  >
    {{ initial }}
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  name?: string
  color?: string
  size?: number
}>(), {
  name: 'あなた',
  color: '#1da1f2',
  size: 40
})

const initial = computed(() => props.name.trim().charAt(0) || '?')
</script>

<style scoped>
.user-avatar {
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-weight: 700;
  flex-shrink: 0;
  user-select: none;
}
</style>

// src/components/UserAvatar.tsx
interface Props {
  name?: string
  color?: string
  size?: number
}

export default function UserAvatar({ name = 'あなた', color = '#1da1f2', size = 40 }: Props) {
  const initial = name.trim().charAt(0) || '?'
  return (
    <div
      className="user-avatar"
      style={{
        backgroundColor: color,
        width: size,
        height: size,
        fontSize: Math.round(size * 0.42),
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
        fontWeight: 700,
        flexShrink: 0,
        userSelect: 'none'
      }}
    >
      {initial}
    </div>
  )
}
